---
title: "Analyse de DEG_des_CML_res02"
output: html_document
date: "2026-05-07"
---

```{r}
#BiocManager::install("org.Mm.eg.db")
library(org.Mm.eg.db)
library(enrichplot)
library(msigdbr)
library(fgsea)
library(clusterProfiler)

# Pour le cluster 4
deg_cluster4_CML_intà6 <- FindMarkers(
  data_CML_intà6,
  ident.1 = "4",
  logfc.threshold = 0.25,
  min.pct = 0.1
)
deg_cluster4_CML_intà6

# Sélectionner les gènes significatifs du cluster
deg_sig <- deg_cluster4_CML_intà6[
  deg_cluster4_CML_intà6$p_val_adj < 0.05 &
  abs(deg_cluster4_CML_intà6$avg_log2FC) > 0.5,
]  # filtrage sur P_value et avg_log2FC
genes4 <- rownames(deg_sig) # récupération du symbol des gènes du cluster 
genes4
genes4_df <- data.frame(Gene = genes4)
write.xlsx(
  genes4_df,
  "/home/afall/r-docker/Analyses_SnRNA_10_2025/Sans_Balbc/Version_nautilus/Analyses_SnRNA_01_2026/New_Analyse_Pathway_CML_res02_avec_filtrage_spécifique_descommandes/DEG_cluster4_CML_res02_filtrésurpvalueetavglog2FC.xlsx",
  rowNames = TRUE
)

background_genes4 <- rownames(deg_cluster4_CML_intà6)
background_genes4

# Analyse d'enrichissement avec la base de donnée GO
#enrichGO(genes, OrgDb, keytype = "SYMBOL", ont = "MF", pvalueCutoff = 0.05, pAdjustMethod = "BH", universe, qvalueCutoff = 0.2, minGSSize = 10, maxGSSize = 500, readable = FALSE) # cette commande vient de la documentation de clusterprofiler: https://www.rdocumentation.org/packages/clusterProfiler/versions/3.0.4/topics/enrichGO
# Nous allons l'adapter à nos données dans la commande suivante
ego <- enrichGO(
  gene = genes4,
  universe = background_genes4,
  OrgDb = org.Mm.eg.db,
  keyType = "SYMBOL",
  ont = "BP",
  pAdjustMethod = "BH",
  pvalueCutoff = 0.01,
  qvalueCutoff = 0.05,
  minGSSize = 10,
  maxGSSize = 300,
  readable = TRUE
)
ego <- simplify(
  ego,
  cutoff = 0.6,
  by = "p.adjust",
  select_fun = min
)
ego
head(ego@result)
# Visualisation 
D <- dotplot(ego, showCategory = 5) + ggtitle("GO BP enrichment (cluster4_CML_intà6 vs les autres clusters)")
D
ggsave(filename = "/home/afall/r-docker/Analyses_SnRNA_10_2025/Sans_Balbc/Version_nautilus/Analyses_SnRNA_01_2026/New_Analyse_Pathway_CML_res02_avec_filtrage_spécifique_descommandes/Dotplot_enrichGO_cluster4_CML_res02_filtrageavgetpvalue.png", plot = D, width = 12, height = 7, dpi = 300)

# Pour le cluster 3
deg_cluster3_CML_intà6 <- FindMarkers(
  data_CML_intà6,
  ident.1 = "3",
  logfc.threshold = 0.25,
  min.pct = 0.1
)
deg_cluster3_CML_intà6
write.xlsx(deg_cluster3_CML_intà6,
             "/home/afall/r-docker/Analyses_SnRNA_10_2025/Sans_Balbc/Version_nautilus/Analyses_SnRNA_01_2026/New_Umap_des_CML_TRUEVERSION/DEG_cluster3_CML_intà6_res02.xlsx",
             rowNames = TRUE)  # Le fichier DEG_cluster3_CML_intà6.xlsx contient les DEG du cluster 3 obtenu en comparant le cluster 3 aux autres clusters (sauf le 3) de la population des CML 
# Sélectionner les gènes significatifs du cluster
deg_sig <- deg_cluster3_CML_intà6[
deg_cluster3_CML_intà6$p_val_adj < 0.05, ]
deg_sig  # Contient uniquement les DEG du cluster 3 qui ont un p_val_adj < 0.05 
genes3 <- rownames(deg_sig) # genes3 ici pour dire les gènes du cluster 3
genes3
genes3_df <- data.frame(Gene = genes3)
write.xlsx(
  genes3_df,
  "/home/afall/r-docker/Analyses_SnRNA_10_2025/Sans_Balbc/Version_nautilus/Analyses_SnRNA_01_2026/New_Umap_des_CML_TRUEVERSION/DEG_filtré_cluster3_CML_intà6_pvaladj<005_res02.xlsx",
  rowNames = TRUE
)
background_genes4 <- rownames(deg_cluster4_CML_intà6)
background_genes4
ego <- enrichGO(
  gene = genes4,
  universe = background_genes4,
  OrgDb = org.Mm.eg.db,
  keyType = "SYMBOL",
  ont = "BP",
  pAdjustMethod = "BH",
  pvalueCutoff = 0.01,
  qvalueCutoff = 0.05,
  minGSSize = 10,
  maxGSSize = 300,
  readable = TRUE
)
ego <- simplify(
  ego,
  cutoff = 0.6,
  by = "p.adjust",
  select_fun = min
)
ego
head(ego@result)
D <- dotplot(ego, showCategory = 10) + ggtitle("GO BP enrichment (cluster3_CML_intà6 vs les autres clusters)")
D
ggsave(filename = "/home/afall/r-docker/Analyses_SnRNA_10_2025/Sans_Balbc/Version_nautilus/Analyses_SnRNA_01_2026/New_analysis_CML_TRUEVERSION/Dotplot_enrichGO_cluster3_CML_res02_intà6.png", plot = D, width = 12, height = 7, dpi = 300)
# Avec la base de donnée KEGG
ekegg <- enrichKEGG(
gene = genes3,
organism = "mmu"
)
ekegg  #### KEGG ne nous donne pas d'enrichissement ici
library(ReactomePA)
ereact <- enrichPathway(gene = genes3, organism="mouse")
ereact  #### Reactome ne nous donne pas d'enrichissement également

# Pour le cluster 0
deg_cluster0_CML_intà6 <- FindMarkers(
  data_CML_intà6,
  ident.1 = "0",
  logfc.threshold = 0.25,
  min.pct = 0.1
)
deg_cluster0_CML_intà6
write.xlsx(deg_cluster0_CML_intà6,
             "/home/afall/r-docker/Analyses_SnRNA_10_2025/Sans_Balbc/Version_nautilus/Analyses_SnRNA_01_2026/New_Umap_des_CML_TRUEVERSION/DEG_cluster0_CML_intà6_res02.xlsx",
             rowNames = TRUE)  # Le fichier DEG_cluster0_CML_intà6.xlsx contient les DEG du cluster 0 obtenu en comparant le cluster 0 aux autres clusters (sauf le 0) de la population des CML 
# Sélectionner les gènes significatifs du cluster
deg_sig <- deg_cluster0_CML_intà6[
deg_cluster0_CML_intà6$p_val_adj < 0.05, ]
deg_sig  # Contient uniquement les DEG du cluster 0 qui ont un p_val_adj < 0.05 
genes0 <- rownames(deg_sig) # genes0 ici pour dire les gènes du cluster 0
genes0
genes0_df <- data.frame(Gene = genes0)
write.xlsx(
  genes0_df,
  "/home/afall/r-docker/Analyses_SnRNA_10_2025/Sans_Balbc/Version_nautilus/Analyses_SnRNA_01_2026/New_Umap_des_CML_TRUEVERSION/DEG_filtré_cluster0_CML_intà6_pvaladj<005_res02.xlsx",
  rowNames = TRUE
)

library(clusterProfiler)
# Avec la base de donnée GO
ego <- enrichGO(
gene = genes0,
OrgDb = org.Mm.eg.db,
keyType = "SYMBOL",
ont = "BP"
)
ego
head(ego@result)
# Visualisation 
D <- dotplot(ego, showCategory = 10) + ggtitle("GO BP enrichment (cluster0_CML_intà6 vs les autres clusters)")
D
ggsave(filename = "/home/afall/r-docker/Analyses_SnRNA_10_2025/Sans_Balbc/Version_nautilus/Analyses_SnRNA_01_2026/New_analysis_CML_TRUEVERSION/New_Dotplot_enrichGO_cluster0_CML_intà6.png", plot = D, width = 12, height = 7, dpi = 300)
# Avec la base de donnée KEGG
ekegg <- enrichKEGG(
gene = genes0,
organism = "mmu"
)
ekegg  #### KEGG ne nous donne pas d'enrichissement ici
library(ReactomePA)
ereact <- enrichPathway(gene = genes0, organism="mouse")
ereact  #### Reactome ne nous donne pas d'enrichissement également

# Pour le cluster 1
deg_cluster1_CML_intà6 <- FindMarkers(
  data_CML_intà6,
  ident.1 = "1",
  logfc.threshold = 0.25,
  min.pct = 0.1
)
deg_cluster1_CML_intà6
write.xlsx(deg_cluster1_CML_intà6,
             "/home/afall/r-docker/Analyses_SnRNA_10_2025/Sans_Balbc/Version_nautilus/Analyses_SnRNA_01_2026/New_Umap_des_CML_TRUEVERSION/DEG_cluster1_CML_intà6_res02.xlsx",
             rowNames = TRUE)  
# Sélectionner les gènes significatifs du cluster
deg_sig <- deg_cluster1_CML_intà6[
deg_cluster1_CML_intà6$p_val_adj < 0.05, ]
deg_sig 
genes1 <- rownames(deg_sig) 
genes1
genes1_df <- data.frame(Gene = genes1)
write.xlsx(
  genes1_df,
  "/home/afall/r-docker/Analyses_SnRNA_10_2025/Sans_Balbc/Version_nautilus/Analyses_SnRNA_01_2026/New_Umap_des_CML_TRUEVERSION/DEG_filtré_cluster1_CML_intà6_pvaladj<005_res02.xlsx",
  rowNames = TRUE
)

# Avec la base de donnée GO
ego <- enrichGO(
gene = genes1,
OrgDb = org.Mm.eg.db,
keyType = "SYMBOL",
ont = "BP"
)
ego
head(ego@result)
# Visualisation 
D <- dotplot(ego, showCategory = 10) + ggtitle("GO BP enrichment (cluster1_CML_intà6 vs les autres clusters)")
D
ggsave(filename = "/home/afall/r-docker/Analyses_SnRNA_10_2025/Sans_Balbc/Version_nautilus/Analyses_SnRNA_01_2026/New_analysis_CML_TRUEVERSION/Dotplot_enrichGO_cluster1_CML_res02_intà6.png", plot = D, width = 12, height = 7, dpi = 300)
# Avec la base de donnée KEGG
ekegg <- enrichKEGG(
gene = genes1,
organism = "mmu"
)
ekegg  #### KEGG ne nous donne pas d'enrichissement ici
ereact <- enrichPathway(gene = genes1, organism="mouse")
ereact  #### Reactome ne nous donne pas d'enrichissement également

# Pour le cluster 2
deg_cluster2_CML_intà6 <- FindMarkers(
  data_CML_intà6,
  ident.1 = "2",
  logfc.threshold = 0.25,
  min.pct = 0.1
)
deg_cluster2_CML_intà6
write.xlsx(deg_cluster2_CML_intà6,
             "/home/afall/r-docker/Analyses_SnRNA_10_2025/Sans_Balbc/Version_nautilus/Analyses_SnRNA_01_2026/New_Umap_des_CML_TRUEVERSION/DEG_cluster2_CML_intà6_res02.xlsx",
             rowNames = TRUE)  
# Sélectionner les gènes significatifs du cluster
deg_sig <- deg_cluster2_CML_intà6[
deg_cluster2_CML_intà6$p_val_adj < 0.05, ]
deg_sig 
genes2 <- rownames(deg_sig) 
genes2
genes2_df <- data.frame(Gene = genes2)
write.xlsx(
  genes2_df,
  "/home/afall/r-docker/Analyses_SnRNA_10_2025/Sans_Balbc/Version_nautilus/Analyses_SnRNA_01_2026/New_Umap_des_CML_TRUEVERSION/DEG_filtré_cluster2_CML_intà6_pvaladj<005_res02.xlsx",
  rowNames = TRUE
)

# Avec la base de donnée GO
ego <- enrichGO(
gene = genes2,
OrgDb = org.Mm.eg.db,
keyType = "SYMBOL",
ont = "BP"
)
ego
head(ego@result)
# Visualisation 
D <- dotplot(ego, showCategory = 10) + ggtitle("GO BP enrichment (cluster2_CML_intà6 vs les autres clusters)")
D
ggsave(filename = "/home/afall/r-docker/Analyses_SnRNA_10_2025/Sans_Balbc/Version_nautilus/Analyses_SnRNA_01_2026/New_analysis_CML_TRUEVERSION/Dotplot_enrichGO_cluster2_CML_res02_intà6.png", plot = D, width = 12, height = 7, dpi = 300)
# Avec la base de donnée KEGG
ekegg <- enrichKEGG(
gene = genes2,
organism = "mmu"
)
ekegg  #### KEGG ne nous donne pas d'enrichissement ici
ereact <- enrichPathway(gene = genes2, organism="mouse")
ereact  #### Reactome ne nous donne pas d'enrichissement également

# Pour le cluster 5
deg_cluster5_CML_intà6 <- FindMarkers(
  data_CML_intà6,
  ident.1 = "5",
  logfc.threshold = 0.25,
  min.pct = 0.1
)
deg_cluster5_CML_intà6
write.xlsx(deg_cluster5_CML_intà6,
             "/home/afall/r-docker/Analyses_SnRNA_10_2025/Sans_Balbc/Version_nautilus/Analyses_SnRNA_01_2026/New_Umap_des_CML_TRUEVERSION/DEG_cluster5_CML_intà6_res02.xlsx",
             rowNames = TRUE)  
# Sélectionner les gènes significatifs du cluster
deg_sig <- deg_cluster5_CML_intà6[
deg_cluster5_CML_intà6$p_val_adj < 0.05, ]
deg_sig 
genes5 <- rownames(deg_sig) 
genes5
genes5_df <- data.frame(Gene = genes5)
write.xlsx(
  genes5_df,
  "/home/afall/r-docker/Analyses_SnRNA_10_2025/Sans_Balbc/Version_nautilus/Analyses_SnRNA_01_2026/New_Umap_des_CML_TRUEVERSION/DEG_filtré_cluster5_CML_intà6_pvaladj<005_res02.xlsx",
  rowNames = TRUE
)

# Avec la base de donnée GO
ego <- enrichGO(
gene = genes5,
OrgDb = org.Mm.eg.db,
keyType = "SYMBOL",
ont = "BP"
)
ego
head(ego@result)
# Visualisation 
D <- dotplot(ego, showCategory = 10) + ggtitle("GO BP enrichment (cluster5_CML_intà6 vs les autres clusters)")
D
ggsave(filename = "/home/afall/r-docker/Analyses_SnRNA_10_2025/Sans_Balbc/Version_nautilus/Analyses_SnRNA_01_2026/New_analysis_CML_TRUEVERSION/Dotplot_enrichGO_cluster5_CML_res02_intà6.png", plot = D, width = 12, height = 7, dpi = 300)
# Avec la base de donnée KEGG
ekegg <- enrichKEGG(
gene = genes5,
organism = "mmu"
)
ekegg  #### KEGG ne nous donne pas d'enrichissement ici
ereact <- enrichPathway(gene = genes5, organism="mouse")
ereact  #### Reactome ne nous donne pas d'enrichissement également

```

```{r}

```



```{r}

```


